- name: varaibles from prompt
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: pls enter your username
    private: false
  - name: PASSWORD
    prompt: pls enter your password
    private: true
  tasks:
  - name: print variable values
    ansible.builtin.debug:
     msg: "usename: {{USERNAME}}, password: {{PASSWORD}}"