- name: create user
  hosts: localhost
  tasks: 
  - name: check roboshop user exist or not
    ansible.builtin.command:
    register: output
  - name: print the command output
    ansible.builtin.debug:
     msg: "output is: {{output}}"