- name: install packages
  hosts: mongodb
  become: yes
  tasks:
  - name: Install a list of packages with a list variable
  ansible.builtin.yum:
    name: "{{ packages }}"
  vars:
    packages:
    - httpd
    - httpd-tools
