- name: install apache2, sqlite3, git on remote servers
  hosts: all
  become: true
  tasks:
    - name: Install packages
      package:
        name: "{{item}}"
        state: present
      loop:
        - apache2
        - sqlite3
        - git
