- name: install packages
  hosts: mongodb
  become: yes
  tasks:
  - name: Install packages
    become: yes
    package:
     name:
       - tmux
       - rsync
       - zsh
       - rsync
       - wget
     state: present
